### Capítulo 2
# Álgebra lineal

El álgebra lineal es una rama de las matemáticas que estudia conceptos tales como vectores y matrices.
VER https://hadrienj.github.io/

### Terminología

* **Escalar**: Número.
* **Vector**: Array de 1 dimensión (Lista de números).
* **Matriz**: Array de 2 dimensiones.
* **Tensor:** Array de más de 2 dimensiones.

<img src="img/scalar-tensor.png" width="400" alt="scalar-tensor">


In [1]:
import numpy as np

In [6]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [7]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

## Traspuesta

<img src="img/transposeMatrix.png" alt="transposeMatrix" width="300">


In [12]:
A_traspuesta = A.T
A_traspuesta

array([[1, 3, 5],
       [2, 4, 6]])

## Suma

In [13]:
B = np.array([[1, 4], [2, 5], [2, 3]])
B

array([[1, 4],
       [2, 5],
       [2, 3]])

In [14]:
C = A + B
C

array([[2, 6],
       [5, 9],
       [7, 9]])

In [11]:
C = A+4
C

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## Producto escalar (dot product)

<img src="img/dotProduct.png" width="400" alt="dotProduct">


In [16]:
B = np.array([[2], [4]])
B

array([[2],
       [4]])

In [17]:
C = np.dot(A, B) # o también A.dot(B)
C

array([[10],
       [22],
       [34]])

## Matriz de identidad

La matriz de identidad $I$ representa al 1 en forma de matriz. Está rellenado por $0$ menos en la diagonal que son $1$.

<img src="img/identity.png" width="150" alt="identity">

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Matriz inversa


In [22]:
A = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
np.linalg.inv(A)

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])

In [ ]:
u = np.array([1, 6])